COPY INTO MDP.RAW.TRUCK_TELEMETRY
    (EVENT, SOURCE_FILE, LOADED_AT)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$START_SCAN_TIME
    FROM @MDP.RAW.TELEMETRY_RAW_STAGE
)
FILE_FORMAT = (
    TYPE = JSON
)
ON_ERROR = ABORT_STATEMENT;